### ISSUE TITLE
TimedFly new translation: lang_hu (Hungarian)

### ISSUE THREAD

**Issue by montlikadani** [Jacxk/TimedFly#1]
@Jacxk 
Welcome!
**I would like to add a new language to your plugin! The name of the new language: lang_hu (Hungarian)**

Download: http://www.mediafire.com/file/jmqd1uub5pi4zqt/lang_hu+(TimedFly).yml
Or: https://pastebin.com/9h3pxsFS

**Comment by Jacxk** [comment]
Thanks for the translation. I really appreciate it, I just added it to the plugins file.
