### ISSUE TITLE
Op unable to purchase timedfly items

### ISSUE THREAD

**Issue by postal291** [Jacxk/TimedFly#11]
Hiya, just like to say, LOVE this plugin, been using it for a while on my home server for me and the kids.
Only problem I'm running into:
I'd like to use it in the same capacity as the kids. (My account is Op, in the admin permission group) I tried changing the FlyModeIfHasPerm to false in the config, and this allowed me to use /fly to enter the timedfly gui instead of just turning on fly, which works as I would intend. However, when I try to purchase the first tier of fly items I get "You cannot do this." and there's no further information in the console or log files.

Using: Spigot 1.12.2, TimedFly 3.2.1, LuckyPerms 4.2.17, EssentialsX 2.15.0.1, Vault 1.6.6
Pastebin of my config.yml https://pastebin.com/L64Qg7vB
Pastebin of my items.yml https://pastebin.com/Q05XF2i2

No timedfly permissions are set for any groups or players. (seems to work great for the kids)

(re-post of comment on the spigot.mc forum)

**Comment by postal291** [comment]
LOL Nevermind, noticed I can actually read your source code... Read through, found the issue.  Didn't have timedfly.fly.onoff set at all, so when I set it to false for my admin group, boom, works as intended.  Again, love the plugin, thanks!

**Comment by Jacxk** [comment]
LOL, don't worry mistakes happen all the time :D
