### ISSUE TITLE
Fly off message mistake and override other cmd

### ISSUE THREAD

**Issue by DahunDev** [Jacxk/TimedFly#12]
1. when fly off, 
player.setAllowFlight(false);          
 **Message.sendMessage(player, languageConfig.getString("Fly.Message.SetOn"));**      

that must be  Message.sendMessage(player, languageConfig.getString("Fly.Message.SetOff"));   

Fly off message mistake

The message of fly off ("/tfly off") is same as fly on("/tfly on")

2. Override other cmd which is smiliar to tfly command.

In My server case, this plugin override strongly essentials' fly command "/fly")

I searched the command "/fly" in this plugin, but there's no that command, but
even I overrided "/fly" command to "/essentials:fly" with VTV1 (VariableTriggers).
The result was same.

In normal case, I overrided "/test" command to "/notest" with VTV1 (VariableTriggers).
The result was excute command "/notest" when using "/test", but 
just this plugin (Timed Fly) does not.

Always run the command "/tfly on ,/tfly off" instead of "/fly".

**Comment by Jacxk** [comment]
sorry about that, I'll have it fixed by tomorrow morning.

**Comment by Jacxk** [comment]
I've fixed the message issue and about the command you need to go to config.yml change *`OpenMenuCommand`* to whatever you like
