### ISSUE TITLE
Problem with tfly command.

### ISSUE THREAD

**Issue by DahunDev** [Jacxk/TimedFly#13]
org.bukkit.command.CommandException: Unhandled exception executing command 'tfly' in plugin TimedFly v3.3.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit.jar:git-Spigot-642f6d2-6103339]

        at com.massivecraft.massivelag.inject.MassiveLagCommandMap.dispatch(MassiveLagCommandMap.java:98) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[craftbukkit.jar:git-Spigo
t-642f6d2-6103339]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:634) [craftbukkit.jar:git-
Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:444) [craftbukkit.jar:git-Spigot-642f6d
2-6103339]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:407) [craftbukkit.jar:git-Spigot-642f6d2
-6103339]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [craftbukkit.jar:git-Spigot-642f6d2
-6103339]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [craftbukkit.jar:git-Spigot-642f6
d2-6103339]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_12_R1.command.ColouredConsoleSender cannot be cast to
 org.bukkit.entity.Player
        at com.timedfly.commands.FlyCMD.onCommand(FlyCMD.java:209) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.jar:git-Spigot-642f6d2-6103339]

        ... 8 more
		

		
>tfly timeleft Cute_Cube
[05:16:43 INFO]: TimedFly >> Usage /tfly timeleft <player>
>tfly timeleft Cute_Cube
[05:16:44 INFO]: TimedFly >> Usage /tfly timeleft <player>
>tfly timeleft Cute_Cube
[05:16:45 INFO]: TimedFly >> Usage /tfly timeleft <player>
>
>tfly timeleft Cute_Cube
[05:16:45 INFO]: TimedFly >> Usage /tfly timeleft <player>
>tfly timeleft Cute_Cube
[05:16:45 INFO]: TimedFly >> Usage /tfly timeleft <player>

[05:22:20 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'tfly' in plugin TimedFly v3.3.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit.jar:git-Spigot-642f6d2-6103339]

        at com.massivecraft.massivelag.inject.MassiveLagCommandMap.dispatch(MassiveLagCommandMap.java:98) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[craftbukkit.jar:git-Spigo
t-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397) [craftbukkit.jar:git
-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1232) [craftbukkit.jar:git-Spigot-642f
6d2-6103339]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [craftbukkit.jar:git-Spigot-642f6d
2-6103339]
        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [craftbukkit.jar:git-Spigot-642f6d2
-6103339]
        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit.jar:git-Spigot-642f6d2-
6103339]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_181]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_181]
        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [craftbukkit.jar:git-Spigot-642f6d2-6103339]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [craftbukkit.jar:git-Spigot-642f6d2
-6103339]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [craftbukkit.jar:git-Spigot-642f6d2
-6103339]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [craftbukkit.jar:git-Spigot-642f6d2
-6103339]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [craftbukkit.jar:git-Spigot-642f6
d2-6103339]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.NullPointerException
        at com.timedfly.commands.FlyCMD.onCommand(FlyCMD.java:217) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit.jar:git-Spigot-642f6d2-6103339]

        ... 15 more

And then, my modified (error fixed) " com.timedfly.commands.FlyCMD."
source code is

package com.timedfly.commands;

import com.timedfly.NMS.NMS;
import com.timedfly.configurations.ConfigCache;
import com.timedfly.configurations.Languages;
import com.timedfly.managers.PlayerManager;
import com.timedfly.utilities.FlyGUI;
import com.timedfly.utilities.Message;
import com.timedfly.utilities.TimeFormat;
import com.timedfly.utilities.Utilities;
import org.apache.commons.lang.StringUtils;
import org.bukkit.Bukkit;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.configuration.file.FileConfiguration;
import org.bukkit.entity.Player;

public class FlyCMD implements CommandExecutor {

    private Languages languages;
    private Utilities utility;
    private FlyGUI flyGUI;
    private NMS nms;

    public FlyCMD(Languages languages, Utilities utility, FlyGUI flyGUI, NMS nms) {
        this.languages = languages;
        this.utility = utility;
        this.flyGUI = flyGUI;
        this.nms = nms;
    }

    @Override
    public boolean onCommand(CommandSender sender, Command cmd, String string, String[] args) {
        FileConfiguration languageConfig = languages.getLanguageFile();

        if (cmd.getName().equalsIgnoreCase("tfly")) {
            if (args.length == 0) {
                if (!ConfigCache.isGuiEnable()) return true;
                if (!(sender instanceof Player)) {
                    Message.sendMessage(sender, "&cOnly Player can use this command");
                    return true;
                }
                Player player = (Player) sender;
                if (ConfigCache.isUsePermission() && !sender.hasPermission(ConfigCache.getPermission())) {
                    Message.sendNoPermission(player, languageConfig, nms);
                    return true;
                }

                if (!utility.isWorldEnabled(player.getWorld())) {
                    Message.sendDisabledWorld(sender, languageConfig);
                    return true;
                }
                flyGUI.openGui(player);

            } else {
                if (args[0].equalsIgnoreCase("help")) Bukkit.getServer().dispatchCommand(sender, "tf help");
                if (args[0].equalsIgnoreCase("help2")) Bukkit.getServer().dispatchCommand(sender, "tf help2");
                if (args[0].equalsIgnoreCase("help3")) Bukkit.getServer().dispatchCommand(sender, "tf help3");
                if (args[0].equalsIgnoreCase("add")) {
                    if (!(sender.hasPermission("timedfly.fly.add") || sender.hasPermission("timedfly.admin"))) {
                        if (sender instanceof Player) Message.sendNoPermission((Player) sender, languageConfig, nms);
                        return true;
                    }
                    if (args.length == 1 || args.length == 2) {
                        Message.sendMessage(sender, "&7사용법: /tfly add <player> <minutes>");
                        return true;
                    }

                    StringBuilder timeString = new StringBuilder();

                    if (StringUtils.isNumeric(args[2])) timeString.append(args[2]);
                    else for (int i = 2; i < args.length; i++) timeString.append(args[i]).append(" ");

                    long time = TimeFormat.timeToSeconds(timeString.toString().trim());

                    if (args[1].equalsIgnoreCase("*")) {
                        Message.sendDebugMessage(this.getClass().getSimpleName() + "&c:AddCmd: &7Adding time to all player", 1);
                        for (Player player : Bukkit.getOnlinePlayers()) {
                            if (!utility.isWorldEnabled(player.getWorld())) continue;
                            PlayerManager playerManager = utility.getPlayerManager(player.getUniqueId());
                            playerManager.addTime((int) time);
                        }
                        Message.sendDebugMessage(this.getClass().getSimpleName() + "&c:AddCmd: &7Success", 2);
                        return true;
                    }

                    Player player = Bukkit.getPlayer(args[1]);
                    if (player == null) {
                        Message.sendMessage(sender, languageConfig.getString("Other.PlayerNotFound"));
                        return true;
                    }

                    if (!utility.isWorldEnabled(player.getWorld())) {
                        Message.sendDisabledWorld(sender, languageConfig);
                        return true;
                    }

                    PlayerManager playerManager = utility.getPlayerManager(player.getUniqueId());

                    playerManager.addTime((int) time);

                    Message.sendMessage(sender, languageConfig.getString("Fly.Message.AddTime").replace("%time%",
                            timeString.toString().trim()).replace("%player%", player.getDisplayName()));
                    Message.sendMessage(player, languageConfig.getString("Fly.Message.AddTimeToPlayer").replace("%time%",
                            timeString.toString().trim()).replace("%player%", sender.getName()));
                    return true;
                }
                if (args[0].equalsIgnoreCase("set")) {
                    if (!(sender.hasPermission("timedfly.fly.set") || sender.hasPermission("timedfly.admin"))) {
                        Message.sendDebugMessage(this.getClass().getSimpleName() + "&c:SetCmd: &7No permission", 1);
                        if (sender instanceof Player) Message.sendNoPermission((Player) sender, languageConfig, nms);
                        return true;
                    }
                    if (args.length == 1 || args.length == 2) {
                        Message.sendMessage(sender, "&7사용법: /tfly set <player> <minutes>");
                        return true;
                    }

                    StringBuilder timeString = new StringBuilder();

                    if (StringUtils.isNumeric(args[2])) timeString.append(args[2]);
                    else for (int i = 2; i < args.length; i++) timeString.append(args[i]).append(" ");

                    long time = TimeFormat.timeToSeconds(timeString.toString().trim());

                    if (args[1].equalsIgnoreCase("*")) {
                        Message.sendDebugMessage(this.getClass().getSimpleName() + "&c:SetCmd: &7Setting time to all player", 2);
                        for (Player player : Bukkit.getOnlinePlayers()) {
                            if (!utility.isWorldEnabled(player.getWorld())) continue;
                            PlayerManager playerManager = utility.getPlayerManager(player.getUniqueId());
                            playerManager.setTime((int) time);
                        }
                        Message.sendDebugMessage(this.getClass().getSimpleName() + "&c:SetCmd: &7Success", 2);
                        return true;
                    }

                    Player player = Bukkit.getPlayer(args[1]);

                    if (player == null) {
                        Message.sendDebugMessage(this.getClass().getSimpleName() + "&c:SetCmd: &7Player not found", 1);
                        Message.sendMessage(sender, languageConfig.getString("Other.PlayerNotFound"));
                        return true;
                    }

                    if (!utility.isWorldEnabled(player.getWorld())) {
                        Message.sendDebugMessage(this.getClass().getSimpleName() + "&c:SetCmd: &7Disabled world", 1);
                        Message.sendDisabledWorld(sender, languageConfig);
                        return true;
                    }

                    PlayerManager playerManager = utility.getPlayerManager(player.getUniqueId());

                    Message.sendDebugMessage(this.getClass().getSimpleName() + "&c:SetCmd: Setting Time", 2);
                    playerManager.setTime((int) time);

                    Message.sendDebugMessage(this.getClass().getSimpleName() + "&c:SetCmd: &7Sending success message", 2);
                    Message.sendMessage(sender, languageConfig.getString("Fly.Message.ToPlayer")
                            .replace("%target%", player.getDisplayName()).replace("%time%", "" + timeString.toString().trim()));
                    Message.sendMessage(player, languageConfig.getString("Fly.Message.FromPlayer")
                            .replace("%player%", sender.getName()).replace("%time%", "" + timeString.toString().trim()));
                    return true;
                }
                if (args[0].equalsIgnoreCase("on")) {
                    if (!(sender instanceof Player)) {
                        Message.sendMessage(sender, "&cOnly Player can use this command");
                        return true;
                    }
                    Player player = (Player) sender;

                    if (!(player.hasPermission("timedfly.fly.onoff") || player.hasPermission("timedfly.admin"))) {
                        Message.sendNoPermission(player, languageConfig, nms);
                        return true;
                    }

                    if (!utility.isWorldEnabled(player.getWorld())) {
                        Message.sendDisabledWorld(sender, languageConfig);
                        return true;
                    }

                    player.setAllowFlight(true);
                    Message.sendMessage(player, languageConfig.getString("Fly.Message.SetOn"));
                    return true;
                }
                if (args[0].equalsIgnoreCase("off")) {
                    if (!(sender instanceof Player)) {
                        Message.sendMessage(sender, "&cOnly Player can use this command");
                        return true;
                    }
                    Player player = (Player) sender;

                    if (!(player.hasPermission("timedfly.fly.onoff") || player.hasPermission("timedfly.admin"))) {
                        Message.sendNoPermission(player, languageConfig, nms);
                        return true;
                    }

                    if (!utility.isWorldEnabled(player.getWorld())) {
                        Message.sendDisabledWorld(sender, languageConfig);
                        return true;
                    }

                    player.setAllowFlight(false);
                    Message.sendMessage(player, languageConfig.getString("Fly.Message.SetOff")); //msg error fix
                    return true;
                }
                if (args[0].equalsIgnoreCase("timeleft")) {
                    Player player;
 
                    **if ( (!(sender instanceof Player)) && args.length == 1    ) { //switching   if() with downside //and add && args.length == 1
                        Message.sendMessage(sender, "&7사용법: &a/tfly timeleft <player>");
                        return true;
                    }
                    
                  // switching if() with upside
                    if (args.length == 1){ player = (Player) sender;
                    } else player = Bukkit.getPlayer(args[1]);**

                    
                    {
                    	
                    	try{

                    PlayerManager playerManager = utility.getPlayerManager(player.getUniqueId());
  
                    
                    if(args.length == 2){
                    if (playerManager.getTimeLeft() > 0) {
                        long timeLeft = playerManager.getTimeLeft();
                        Message.sendMessage(sender, languageConfig.getString("Fly.Message.OthersTimeLeft")
                        		.replace("%player%", player.getName())
                                .replace("%timeleft%", TimeFormat.formatLong(timeLeft)));
                    } else {
                        Message.sendMessage(sender, languageConfig.getString("Fly.Message.OthersTimeLeft")
                        		.replace("%player%", player.getName())
                                .replace("%timeleft%", playerManager.getTimeLeft() != 0 || playerManager.isTimePaused()
                                        ? TimeFormat.formatLong(playerManager.getTimeLeft()) : languageConfig.getString("Format.NoTimeLeft")));
                    }
                    return true;
                    }
                    
                    if (playerManager.getTimeLeft() > 0) {
                        long timeLeft = playerManager.getTimeLeft();
                        Message.sendMessage(sender, languageConfig.getString("Fly.Message.TimeLeft")
                                .replace("%timeleft%", TimeFormat.formatLong(timeLeft)));
                    }else {
                        Message.sendMessage(sender, languageConfig.getString("Fly.Message.TimeLeft")
                                .replace("%timeleft%", playerManager.getTimeLeft() != 0 || playerManager.isTimePaused()
                                        ? TimeFormat.formatLong(playerManager.getTimeLeft()) : languageConfig.getString("Format.NoTimeLeft")));
                        return true;
                    	}
                    
                    }catch (Exception e) {
                    	  Message.sendMessage(sender, "&c오류 발생, 해당 플레이어가 온라인인지 확인해 보세요.");
                    	  return true;
					}
                        Message.sendMessage(sender, "&7사용법 &a/tfly timeleft <player>");
                    	}
                }
                if (args[0].equalsIgnoreCase("stop")) {
                    if (!(sender instanceof Player)) {
                        Message.sendMessage(sender, "&cOnly players can do this");
                        return true;
                    }

                    Player player = (Player) sender;
                    PlayerManager playerManager = utility.getPlayerManager(player.getUniqueId());

                    if (!(player.hasPermission("timedfly.fly.stopresume") || player.hasPermission("timedfly.admin"))) {
                        Message.sendNoPermission(player, languageConfig, nms);
                        return true;
                    }

                    if (!utility.isWorldEnabled(player.getWorld())) {
                        Message.sendDisabledWorld(sender, languageConfig);
                        return true;
                    }

                    if (playerManager.isTimeEnded()) {
                        Message.sendMessage(player, languageConfig.getString("Fly.Message.StopAndResume.NoTime"));
                        return true;
                    }

                    if (ConfigCache.isBossBarTimerEnabled()) playerManager.getBossBarManager().hide();

                    playerManager.stopTimedFly(true, true);
                    playerManager.setTimePaused(true);

                    Message.sendMessage(player, languageConfig.getString("Fly.Message.StopAndResume.Stop"));

                }

                if (args[0].equalsIgnoreCase("resume")) {
                    if (!(sender instanceof Player)) {
                        Message.sendMessage(sender, "&cOnly players can do this");
                        return true;
                    }
                    Player player = (Player) sender;
                    PlayerManager playerManager = utility.getPlayerManager(player.getUniqueId());

                    if (!(player.hasPermission("timedfly.fly.stopresume") || player.hasPermission("timedfly.admin"))) {
                        Message.sendNoPermission(player, languageConfig, nms);
                        return true;
                    }

                    if (!utility.isWorldEnabled(player.getWorld())) {
                        Message.sendMessage(player, languageConfig.getString("Other.DisabledWorld"));
                        return true;
                    }

                    if (playerManager.getTimeLeft() == 0) {
                        Message.sendMessage(player, languageConfig.getString("Fly.Message.StopAndResume.NoTime"));
                        return true;
                    }

                    if (!playerManager.isTimePaused()) {
                        Message.sendMessage(player, languageConfig.getString("Fly.Message.StopAndResume.Already"));
                        return true;
                    }
                    playerManager.startTimedFly();

                    if (ConfigCache.isBossBarTimerEnabled()) playerManager.getBossBarManager().show();
                    Message.sendMessage(player, languageConfig.getString("Fly.Message.StopAndResume.Resume"));

                }
            }
        }
        return true;
    }
}

**Comment by Jacxk** [comment]
You could edit the source code here on github, I'll fix it tho

**Comment by DahunDev** [comment]
Please Add the Console log for Buying. SUCH AS 

    EnabledConsole: '[Kite 서버 비행시간] %player%님이 비행시간 %time%분을 %price%원에 구매하였습니다.'

And, when StopFlyOnGround: true

Is enabled, if player take off to land on timeleft 0 seconds, the player will have infinite flying time, without 0 to No time.

That is one of critical bug.

**Comment by Jacxk** [comment]
Errors had been solved, hopefully, and I added the console log you wanted.
