### ISSUE TITLE
time left is not going to 0

### ISSUE THREAD

**Issue by DahunDev** [Jacxk/TimedFly#15]
time left is not going to 0

the timeleft not going to 0. (Time count stop on timeleft 1 sec)

The timeleft is always above 1 if the time is expired and no addtional buying flight,

**Comment by Jacxk** [comment]
Sorry about that I don't know why the hell I did that.

**Comment by DahunDev** [comment]
The timeleft is not change to NoTimeLeft
If fly time expried, the timeleft is fixed as 1 sec.

**Comment by Jacxk** [comment]
can you try the new update and see if it still does that? [Here](https://www.spigotmc.org/resources/timedfly-3-mysql-support-1-8-1-13.48668/update?update=241211)

**Comment by DahunDev** [comment]
Please update the GitHub Source file to new Source.

**Comment by Jacxk** [comment]
sure, done!
