### ISSUE TITLE
"ASkyblockIntegration: false" Problem

### ISSUE THREAD

**Issue by DahunDev** [Jacxk/TimedFly#19]
"ASkyblockIntegration: false" Problem

When config of
ASkyblockIntegration is set to false,
the plugin still work same as "ASkyblockIntegration: true"

**Comment by Jacxk** [comment]
It should work the same way since if ASkyblockIntegration is true when the plugin loads the Skyblock Integration enables, and for that to happen you `ASkyblockIntegration: true` and ASkyblock in your server
