### ISSUE TITLE
[Issue] Could not pass event PlayerGameModeChangeEvent to TimedFly v3.4.2

### ISSUE THREAD

**Issue by maxlehot1234** [Jacxk/TimedFly#21]
This is the error I have on the console sometimes for no reason. No players online.

**Comment by Estaira** [comment]
I can confirm same issue. Here is more details below.

> 05.01 02:54:55 [Server] ERROR Could not pass event PlayerGameModeChangeEvent to TimedFly v3.4.2
05.01 02:54:55 [Server] INFO org.bukkit.event.EventException: null
05.01 02:54:55 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
05.01 02:54:55 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
05.01 02:54:55 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
05.01 02:54:55 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
05.01 02:54:55 [Server] INFO at net.minecraft.server.v1_12_R1.EntityPlayer.a(EntityPlayer.java:1145) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
05.01 02:54:55 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.setGameMode(CraftPlayer.java:798) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
05.01 02:54:55 [Server] INFO at com.sk89q.worldguard.session.handler.GameModeFlag.updateGameMode(GameModeFlag.java:62) [worldguard-legacy-6.2.2-SNAPSHOT-dist.jar:?]
05.01 02:54:55 [Server] INFO at com.sk89q.worldguard.session.handler.GameModeFlag.onInitialValue(GameModeFlag.java:77) [worldguard-legacy-6.2.2-SNAPSHOT-dist.jar:?]
05.01 02:54:55 [Server] INFO at com.sk89q.worldguard.session.handler.GameModeFlag.onInitialValue(GameModeFlag.java:33) [worldguard-legacy-6.2.2-SNAPSHOT-dist.jar:?]
05.01 02:54:55 [Server] INFO at com.sk89q.worldguard.session.handler.FlagValueChangeHandler.initialize(FlagValueChangeHandler.java:45) [worldguard-legacy-6.2.2-SNAPSHOT-dist.jar:?]
05.01 02:54:55 [Server] INFO at com.sk89q.worldguard.session.Session.initialize(Session.java:116) [worldguard-legacy-6.2.2-SNAPSHOT-dist.jar:?]
05.01 02:54:55 [Server] INFO at com.sk89q.worldguard.session.SessionManager.createSession(SessionManager.java:226) [worldguard-legacy-6.2.2-SNAPSHOT-dist.jar:?]
05.01 02:54:55 [Server] INFO at com.sk89q.worldguard.session.SessionManager.access$200(SessionManager.java:52) [worldguard-legacy-6.2.2-SNAPSHOT-dist.jar:?]
05.01 02:54:55 [Server] INFO at com.sk89q.worldguard.session.SessionManager$2.load(SessionManager.java:74) [worldguard-legacy-6.2.2-SNAPSHOT-dist.jar:?]
05.01 02:54:55 [Server] INFO at com.sk89q.worldguard.session.SessionManager$2.load(SessionManager.java:71) [worldguard-legacy-6.2.2-SNAPSHOT-dist.jar:?]
05.01 02:54:55 [Server] INFO at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
05.01 02:54:55 [Server] INFO at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
05.01 02:54:55 [Server] INFO at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
05.01 02:54:55 [Server] INFO at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
05.01 02:54:55 [Server] INFO at com.google.common.cache.LocalCache.get(LocalCache.java:4154) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
05.01 02:54:55 [Server] INFO at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4158) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
05.01 02:54:55 [Server] INFO at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:5147) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
05.01 02:54:55 [Server] INFO at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:5153) [spigot-1.12.2.jar:git-Spigot-3d850ec-809c399]
05.01 02:54:55 [Server] INFO at com.sk89q.worldguard.session.SessionManager.get(SessionManager.java:253) [worldguard-legacy-6.2.2-SNAPSHOT-dist.jar:?]
05.01 02:54:55 [Server] INFO at com.sk89q.worldguard.session.SessionManager.onPlayerJoin(SessionManager.java:259) [worldguard-legacy-6.2.2-SNAPSHOT-dist.jar:?]
05.01 02:54:55 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
05.01 02:54:55 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
