### ISSUE TITLE
Issue with command and working

### ISSUE THREAD

**Issue by Lc-Smith** [Jacxk/TimedFly#29]
A server owner and friend of mine has found this plugin and planned to use it on his survival server, but after a lot of testing and digression, we have found that the plugin does not function as it should. /tfly <command> commands just output "Correct usage: /tfly" and when a player has payed for the flight, they do not seem to get it. They have the permission timedfly.fly.onoff also.
The server runs on 1.12.2 and just in case you are aware of incompatible plugins, this is the plugin list below. If there are, but the server does not have them, please inform me of them non the less, just to be certain as the server is in beta and more plugins are likely to be added.
CleanroomGenerator, MinePacks, NoNetherRoof, PlaceHolderAPI, PlugMan, NametagEdit, RawMsg, DeluxeTags, SuperTrails, Quests, ViaVersion, FastCraft, Skript, AnimatedScoreboard, BlockQuest, SellGUI, VeinMiner, ClearLag, AdvancedBan, BarGamble, BungeeBridgeC, Chairs, Elevator, SkQuery, ProtocolLib, ChestCleaner, eZProtector, FastAsyncWorldEdit, Reports, MrCore_BukkitImpl, DeluxeMenus, PermissionsEx, TAB, Vault, EZBlocks, CrazyCrates, Trading, HolographicDisplays, GuiBalance, WorldEdit, Essentials, BeastWithDraw, BountyHunters, TimeToReport, DecoHeads, CrazyAuctions, EssentialsChat, PlotSquared, WorldGuard, EssentialsSpawn, WorldGuardExtraFlags, CommandRegions, TimedFly, SilkSpawners, Multiverse-Core, GriefPrevention, BlockParticles, StackMob, ChestShop, CombatTagPlus, AdvancedRegionMarket, RandomTeleport, CrazyEnchantments.

**Comment by Jacxk** [comment]
Check the new updates at https://github.com/Jacxk/TimedFly/releases
