### ISSUE TITLE
TimedFly is using a deprecated method

### ISSUE THREAD

**Issue by viasnake** [Jacxk/TimedFly#30]
The PlaceholderAPI prints the following alert on the console:
```
[PlaceholderAPI] TimedFly is currently using a deprecated method to hook into PlaceholderAPI.
Placeholders for that plugin no longer work.
Please consult [By_Jack] and urge them to update it ASAP.
```

This is an announcement from the Placeholder API.
[2.10.1 Lets have a talk edition](https://www.spigotmc.org/resources/placeholderapi.6245/update?update=276433)

**Comment by Jacxk** [comment]
I'm fixing that and it'll be available in v4 of the plugin.
