### ISSUE TITLE
StopTimerOnLeave not working

### ISSUE THREAD

**Issue by YoussefAlBassam** [Jacxk/TimedFly#36]
Hello, I have set the "StopTimerOnLeave" option to "false" but the timer still stops when the players leave the server. It is crucial that I get this fixed because I don't want players to take advantage of leaving the server. How can I fix this issue?

Minecraft version: 1.12.2
TimedFly version: Latest one

Console message when player leaves:
https://gyazo.com/7733de5e286cf5c5737c2740458a667a

Pic of config:
https://gyazo.com/27feae0c7b446e6c0ff6a4c73c293a84

**Comment by Jacxk** [comment]
If you're using the version on spigot then try using the one I publish here on github, just go to the [releases](https://github.com/Jacxk/TimedFly/releases) and you'll find it there. I'll be releasing a new version soon, in less than a day so you should wait for it I think. But be ware that these versions are still on beta.

**Comment by YoussefAlBassam** [comment]
I tried the latest BETA version but it is really bugged on my server. have a look:
https://gyazo.com/b428e260693e9972d21aadb6c2a5f062

It is not allowing me to execute any command that relates to /tfly or /timedfly

Is there any way that you could perhaps fix this issue on the main plugin (the one on spigot)?

I am very grateful for this plugin, but this issue is really making it hard for me to use it at all on my server :/ I would love for it to be fixed. Thank you.

**Comment by Jacxk** [comment]
Check the new updates at https://github.com/Jacxk/TimedFly/releases I think you wont have those issues anymore
