### ISSUE TITLE
PlayerPoints error

### ISSUE THREAD

**Issue by NicoNekoDev** [Jacxk/TimedFly#37]
https://pastebin.com/3gQVAanZ

**Comment by Jacxk** [comment]
Can you provide me the link of the plugin. I probably have the wrong plugin.

**Comment by NicoNekoDev** [comment]
https://dev.bukkit.org/projects/playerpoints
The plugin is outdated but it's still works.
I use the beta version.
The API has a change: PlayerPoints.class have now a method called getAPI() which returns PlayerPointsAPI.class

**Comment by NicoNekoDev** [comment]
I resolved myself everything. I have removed PlayerPoints (and any plugin that does not have a maven repo). I also added 1.15 support.

**Comment by Jacxk** [comment]
So you didnt need support for it? 
Im also going to add support ror 1.15 later today.

**Comment by NicoNekoDev** [comment]
Now I don't, but I'll be nice if you could release a working version. I also found that the GUI and /fly set <player> <time> do not work properly (in my updated version). I'm considering doing my own version of a timed fly plugin. Nowadays people likes lightweight plugins with small things, letting big plugins do the rest of the work for them (talking about flying vouchers). I have a voucher plugin that runs a command in the console and adds flytime for players, tho the command does not work. :( Also a vote plugin that does the same thing. (Sorry for offtopic)

**Comment by Jacxk** [comment]
Yeah I get your point, and I was going to make the plugin modular, like: you add some files to a folder to add the gui, etc.

**Comment by NicoNekoDev** [comment]
I present to you: Wingman
https://imgur.com/a/cWMItai

This is the first alpha version that does not have any errors. Most of the API & codding is from my plugin CitizensBooks.
Here's the source code: https://github.com/nicuch/Wingman

**Comment by Jacxk** [comment]
Nice, imma have you teach me how to make the updater like that, cuz I never understood how it worked.

**Comment by NicoNekoDev** [comment]
Sure, but that's just a checker, not an actual updater. The actual updater is much harder and complicated for me to make.
