### ISSUE TITLE
Not an issue but a question

### ISSUE THREAD

**Issue by DopeDealers** [Jacxk/TimedFly#39]
Would it be possible with this system to add a new currency i.e
items?

Currency: 'vault' # Available currencies: none, vault, tokenmanager, playerpoints, levels, exp

**Comment by Jacxk** [comment]
Can you explain a little bit more on that?

**Comment by DopeDealers** [comment]
Yeah sure, so with your current currencies i see that only money and exp points are available etc.
but instead of those could we choose to have it take items from a player i.e Currency: 'item'
and then under choose what item we want and the amount

**Comment by Jacxk** [comment]
Sounds like a good idea, I'll implement it now and it'll be ready on the next update
