### ISSUE TITLE
Error occurred while enabling TimedFly

### ISSUE THREAD

**Issue by vanduck241** [Jacxk/TimedFly#40]
Paper 1.12.2
Plugin version: latest (4.3.0-BETA)
Happens when enabling the plugin.
Logs: https://pastebin.com/ruYVcYHR
Maybe cause i use the plugin on 1.12.2 while it says _Tested Minecraft Versions: 1.14, 1.15_

Sorry for my bad English. Google translate helps me alot!

**Comment by Jacxk** [comment]
Check can I see your Items.yml file?

**Comment by vanduck241** [comment]
Yeah sure: https://pastebin.com/jFU9USM2

**Comment by Jacxk** [comment]
I see the issue, the items.yml file changed in the latest version it should look like this at the end of the file (or in all items)

```yml
    ​Currency​:
      ​Type​: ​'​vault​'​ ​#​ Available currencies: none, vault, tokenmanager, playerpoints, levels, exp, item​
      ​#​ If the TYPE is 'item' what's bellow will take effect​
      ​Item​: ​DIAMOND
```
Item can be anything you want but it wont take effect until the type is `item`

**Comment by vanduck241** [comment]
Thank you for helping me but i'm still got that error.

Logs: https://pastebin.com/jYQNtF0F
Items.yml: https://pastebin.com/0WM8LEPZ

**Comment by Jacxk** [comment]
Did you make sure you saved the file before restarting?

**Comment by vanduck241** [comment]
yeah i did save it, then stop the server and start it again
