### ISSUE TITLE
Fly work in disabled world because of attack mode

### ISSUE THREAD

**Issue by BigMinnie** [Jacxk/TimedFly#42]
So new bug with disabled worlds and attack mode. When you enter the disabled world fly does not work as it should but as soon as you take damage or deal damage to someone you enter the "attack mode" or better to say, you quit attack mode and you can enable the fly. See Image
![Screenshot_1](https://user-images.githubusercontent.com/32235570/78591895-7092ce80-7844-11ea-852c-d29c76f8605b.png)

**Comment by Jacxk** [comment]
Hmm, I guess I didn't tested that. I'll check it out and fix it ASAP.
