### ISSUE TITLE
NBTAPI Outdated

### ISSUE THREAD

**Issue by giovstr** [Jacxk/TimedFly#53]
[Server] WARN [NBTAPI] Please update the NBTAPI or the plugin that contains the api(nag the mod author when the newest release has an old version, not the NBTAPI dev)!
26.03 12:40:02 [Server] WARN [NBTAPI] Current Version: '2.9.1' Newest Version: 2.9.2'
26.03 12:40:02 [Server] WARN [NBTAPI] The NBT-API located at 'package me.jackint0sh.timedfly.hooks.nbtapi' seems to be outdated!
26.03 12:40:01 [Server] INFO ... 21 more
26.03 12:40:01 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
26.03 12:40:01 [Server] INFO at me.jackint0sh.timedfly.commands.Main.onCommand(Main.java:50) ~[TimedFly-4.4.2-BETA-shaded (1).jar:?]
26.03 12:40:01 [Server] INFO at me.jackint0sh.timedfly.flygui.FlyItemCreator.openMenu(FlyItemCreator.java:62) ~[TimedFly-4.4.2-BETA-shaded (1).jar:?]
26.03 12:40:01 [Server] INFO at me.jackint0sh.timedfly.flygui.inventories.MainMenu.create(MainMenu.java:69) ~[TimedFly-4.4.2-BETA-shaded (1).jar:?]
26.03 12:40:01 [Server] INFO at me.jackint0sh.timedfly.flygui.inventories.MainMenu.create(MainMenu.java:22) ~[TimedFly-4.4.2-BETA-shaded (1).jar:?]
26.03 12:40:01 [Server] INFO at me.jackint0sh.timedfly.flygui.Item.<init>(Item.java:54) ~[TimedFly-4.4.2-BETA-shaded (1).jar:?]
26.03 12:40:01 [Server] INFO at me.jackint0sh.timedfly.versions.ServerVersion.setNBT(ServerVersion.java:30) ~[TimedFly-4.4.2-BETA-shaded (1).jar:?]
26.03 12:40:01 [Server] INFO at me.jackint0sh.timedfly.hooks.nbtapi.NBTCompound.setString(NBTCompound.java:101) ~[TimedFly-4.4.2-BETA-shaded (1).jar:?]
26.03 12:40:01 [Server] INFO at me.jackint0sh.timedfly.hooks.nbtapi.NBTReflectionUtil.<clinit>(NBTReflectionUtil.java:36) ~[TimedFly-4.4.2-BETA-shaded (1).jar:?]
26.03 12:40:01 [Server] INFO Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Class.getDeclaredField(String)" because the return value of "me.jackint0sh.timedfly.hooks.nbtapi.utils.nmsmappings.ClassWrapper.getClazz()" is null
26.03 12:40:01 [Server] INFO ... 21 more

**Comment by giovstr** [comment]
version 1.18.2

**Comment by konfix** [comment]
yeah, we can't even run the main command with the outdated nbtapi.
